name: testing-gh-actions
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'test'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'main'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
